module.exports = app => {
    const associate = require("../controllers/associate.controller");
    const auth = require("../middlewares/auth");

    var router = require("express").Router();

    router.get("/associatelist", auth, associate.GetAssociateList);
    router.post("/saveassociate", auth, associate.SaveAssociate);
    router.post("/deleteassociate", auth, associate.DeleteAssociate);
    router.post("/saveassociateentitytype", auth, associate.SaveAssociateEntityType);
    router.get("/getassociateentitytypebyassociateid/:Id", auth, associate.GetAssociateEntityTypeByAssociateId);
    router.post("/saveassociatephotoiddetail", auth, associate.SaveAssociatePhotoIdDetail);
    router.post("/saveassociatecommunication", auth, associate.SaveAssociateCommunication);
    router.post("/saveassociatebank", auth, associate.SaveAssociateBank);
    router.get("/getassociatesemailbyassociateid/:Id", auth, associate.GetAssociatesEmailByAssociateId);
    router.post("/saveassociateotherdetail", auth, associate.SaveAssociateOtherDetail);
    router.post("/saveassociatelicensedetail", auth, associate.SaveAssociateLicenseDetail);
    router.post("/saveassociatecertificate", auth, associate.SaveAssociateCertificate);
    router.post("/saveassociatenominee", auth, associate.SaveAssociateNominee);
    router.post("/saveassociatenomineeguardian", auth, associate.SaveAssociateNomineeGuardian);
    router.get("/getcommunicationdetailsbyassociateid/:Id", auth, associate.GetCommunicationDetailsByAssociateId);
    router.get("/getcommercialsbyassociateid/:Id", auth, associate.GetCommercialsByAssociateId);
    router.post("/saveassociatecommercial", auth, associate.SaveAssociateCommercial);
    router.get("/getassociateslist", auth, associate.GetAssociatesList);
    router.get("/getassociategeneralinfobyassociateid/:Id", auth, associate.GetAssociateGeneralInfoByAssociateId);
    router.get("/getassociateentitydetailsbyassociateid/:Id", auth, associate.GetAssociateEntityDetailsByAssociateId);
    router.get("/getassociatephotoiddetailsbyassociateid/:Id", auth, associate.GetAssociatePhotoIdDetailsByAssociateId);
    router.get("/getassociatecommunicationdetailsbyassociateid/:Id", auth, associate.GetAssociateCommunicationDetailsByAssociateId);
    router.get("/getassociatebankdetailsbyassociateid/:Id", auth, associate.GetAssociateBankDetailsByAssociateId);
    router.get("/getassociateotherdetailsbyassociateid/:Id", auth, associate.GetAssociateOtherDetailsByAssociateId);
    router.get("/getassociatelicensedetailsbyassociateid/:Id", auth, associate.GetAssociateLicenseDetailsByAssociateId);
    router.get("/getassociatecertificatedetailsbyassociateid/:Id", auth, associate.GetAssociateCertificateDetailsByAssociateId);
    router.get("/getassociatenomineedetailsbyassociated/:Id", auth, associate.GetAssociateNomineeDetailsByAssociateId);
    router.get("/getassociatenomineeguardiandetailsbyassociateid/:Id", auth, associate.GetAssociateNomineeGuardianDetailsByAssociateId);
    router.get("/getassociatecommercialdetailsbyassociateid/:Id", auth, associate.GetAssociateCommercialDetailsByAssociateId);
    router.post("/saveassociaterights", auth, associate.SaveAssociateRights);
    router.post("/saveassociatebsefile", auth, associate.SaveAssociateBSEFile);
    router.get("/getassociatedownloaddocumentsdetailsbyassociateid/:Id", auth, associate.GetAssociateDownloadDocumentsDetailsByAssociateId);
    router.post("/saveassociateuploaddetails", auth, associate.SaveAssociateUploadDetails);
    router.get("/getassociateempanelmentformdetailsbyassociateid/:Id", auth, associate.GetAssociateEmpanelmentFormDetailsByAssociateId);
    router.get("/getassociateindividual/:Id", auth, associate.GetAssociateIndividual);
    router.get("/gettermscondtionbyassociate", auth, associate.GetTermsCondtionByAssociate);
    router.get("/getmenuoptions/:AssociateId", auth, associate.GetMenuOptions);
    router.get("/getnotification", auth, associate.GetNotification);
    router.post("/saveassociaterejection", auth, associate.SaveAssociateRejection);
    router.get("/getdocument/:associateId/:Name/:FileName", auth, associate.GetAssociateDocuments);
    router.post("/sendnotificationsupervisor", auth, associate.SendNotificationSupervisor);
    router.post("/sendselfnotificationsupervisor", auth, associate.SendSelfNotificationSupervisor);
    router.post("/updatesupervisorverification", auth, associate.UpdateAdminVerification);
    router.get("/getassociateformbyassociateid/:Id", auth, associate.GetAssociateFormByAssociateId);
    router.get("/getassociateprogress/:Id", auth, associate.GetAssociateProgress);
    router.get("/getassociatelogbyassociateid/:Id", auth, associate.GetAssociateViewLogByAssociateId);
    router.get("/getfilterassociatestates", auth, associate.GetFilterAssociateStates);
    router.get("/getfilterassociatecities", auth, associate.GetFilterAssociateCities);
    router.get("/getfilterassociates", auth, associate.GetFilterAssociates);
    router.get("/getfilterassociatestatus", auth, associate.GetFilterAssociateStatus);
    router.get("/getassociateexceldata", auth, associate.GetAssociateExcelData);
    router.post("/sendrejectionnotificationsupervisor", auth, associate.SendRejectionNotificationSupervisor);
    router.post("/sendassociateresetpasswordlink", auth, associate.SendAssociateResetPasswordLink);
    router.post("/resendassociateselfverificationemail", auth, associate.ResendAssociateSelfVerificationEmail);

    app.use("/api/associate", router);
};