module.exports = app => {
    const client = require("../controllers/client.controller");
    const auth = require("../middlewares/auth");

    var router = require("express").Router();

    router.post("/saveintroduction", auth, client.SaveClientIntroduction);
    router.get("/getclientbyid/:Id", auth, client.GetClientById);
    router.get("/getclientkycfamilybyclientid/:ClientId", auth, client.GetClientKycFamilyByClient);
    router.get("/getclientfamilybyclientid/:ClientId", auth, client.GetClientFamilyByClientId);
    router.get("/getclientkyccompanybyclientid/:ClientId", auth, client.GetClientKycCompanyByClient);
    router.post("/savekycdetails", auth, client.SaveClientKycDetails);
    router.get("/getclientkycprofilesbyclientid/:ClientId", auth, client.GetClientKycProfilesByClient);
    router.get("/getclientfamilybyid/:Id", auth, client.GetClientFamilyById);
    router.get("/getclientcompanybyid/:Id", auth, client.GetClientCompanyById);
    router.get("/getguardians/:ClientId", auth, client.GetClientGuardiansByClient);
    router.get("/getkycfamilyprofile/:ClientFamilyId", auth, client.GetClientKycProfileFamily);
    router.get("/getkyccompanyprofile/:ClientCompanyId", auth, client.GetClientKycProfileCompany);
    router.post("/savekycprofile", auth, client.SaveClientKycProfile);
    router.get("/getkycfamilyaddress/:ClientFamilyId", auth, client.GetClientKycAddressFamily);
    router.get("/getkyccompanyaddress/:ClientCompanyId", auth, client.GetClientKycAddressCompany);
    router.post("/savekycaddress", auth, client.SaveClientKycAddress);
    router.get("/getkycfamilybank/:ClientFamilyId", auth, client.GetClientKycBankFamily);
    router.get("/getkyccompanybank/:ClientCompanyId", auth, client.GetClientKycBankCompany);
    router.post("/savekycbank", auth, client.SaveClientKycBank);
    router.get("/getclientassetallocation/:ClientId", auth, client.GetClientAssetAllocation);
    router.post("/saveassetallocation", auth, client.SaveClientAssetAllocation);
    router.get("/getclientprofileaccount/:ClientId/:FirstAccountHolderId/:SecondAccountHolderId", auth, client.GetClientKycProfileAccount);
    router.get("/getclientprofileaccountnominee/:ClientId/:FirstAccountHolderId/:SecondAccountHolderId/:ThirdAccountHolderId/:FirstNomineeId/:SecondNomineeId", auth, client.GetClientKycProfileAccountNominee);
    router.get("/getclientprofileaccountnomineeguardians/:ClientId/:FirstAccountHolderId/:SecondAccountHolderId/:ThirdAccountHolderId/:NomineeId", auth, client.GetClientKycProfileAccountNomineeGuardians);
    router.get("/getclientprofileaccountbank/:ClientId/:FirstAccountHolderId", auth, client.GetClientKycProfileAccountBank);
    router.get("/getclientprofileaccountotherbank/:ClientId/:FirstAccountHolderId/:ClientKycBankId", auth, client.GetClientKycProfileAccountOtherBank);
    router.get("/getaccounts/:ClientId", auth, client.GetClientAccount);
    router.post("/saveaccount", auth, client.SaveClientAccount);
    router.get("/getmandates/:ClientId", auth, client.GetClientMandates);
    router.get("/getkycbanksmandate/:ClientAccountId", auth, client.GetClientKycBankMandate);
    router.post("/savemandate", auth, client.SaveClientAccountMandate);
    router.get("/getdefaultaddress/:ClientId", auth, client.GetClientDefaultAddress);
    router.get("/getdocument/:ClientKycProfileId/:Name/:FileName", auth, client.GetClientDocument);
    router.get("/getaccountdocuments/:ClientId", auth, client.GetClientAccountDocuments);
    router.get("/getaccountdocument/:ClientAccountId/:ClientAccountMandateId/:Name/:FileName", auth, client.GetClientAccountDocument);
    router.post("/sendnotificationassociateadmin", auth, client.SendNotificationAssociateAdmin);
    router.get("/getaccountuploaddocuments/:AccountId", auth, client.GetClientAccountUploadDocuments);
    router.get("/getclientprogress/:Id", auth, client.GetClientProgress);
    router.get("/getaccountbyfirstholder/:ClientId/:ClientKycProfileId", auth, client.GetClientAccountByFirstHolder);
    router.get("/getclientaccountdetails/:Id", auth, client.GetClientAccountDetails);
    router.post("/saveapprovedclientaccount", auth, client.SaveApprovedClientAccount);
    router.post("/saveclientaccountupload", auth, client.SaveClientAccountUploadDocument);
    router.get("/getclientaccountlistbyassociateid/:Id", auth, client.GetClientAccountListByAssociateId);
    router.get("/getassociateclientaccountlist/:Id", auth, client.GetAssociateClientAccountList);
    router.get("/getclientaccountassetallocationbyclientaccountid/:Id", auth, client.GetClientAccountAssetAllocationByClientAccountId);
    router.get("/getclientmandatedetailsbyclientaccountid/:Id", auth, client.GetClientMandateDetailsByClientAccountId);
    router.get("/getclientaccountinfo/:Id", client.GetClientAccountDetails);
    router.get("/getappuserclientprofiles/:ClientId", client.GetAppUserClientProfiles);
    router.post("/savepreferences", auth, client.SaveClientPreferences);
    router.post("/delete", auth, client.DeleteClient);
    router.get("/gettransactionprofiles/:AssociateId", auth, client.GetClientTransactionProfiles);
    router.get("/getclientaccountlistbyprofile/:AssociateId/:PANCardNumber/:FirstHolderName", auth, client.GetClientAccountListByAssociateIdProfile);
    router.get("/getclientaccountaum/:UCC", auth, client.GetClientAccountAumSummary);
    router.get("/getclientaccountportfolioaum/:UCC/:PortfolioTypeCode/:PlanTypeCode/:AsOnDate", auth, client.GetClientAccountPortfolioAumSummary);
    router.get("/getclientaccountportfolioholding/:UCC/:PortfolioTypeCode/:PlanTypeCode/:AsOnDate", auth, client.GetClientAccountPortfolioHolding);
    router.get("/getclientaccountportfolioholdingtransaction/:FolioNumber/:ProductCode/:AsOnDate", auth, client.GetClientAccountPortfolioHoldingSchemeTransactions);
    router.get("/downloadclientholdingreport/:UCC", auth, client.DownloadClientAccountPortfolioHoldingReport);
    router.get("/emailclientholdingreport/:UCC", auth, client.EmailClientAccountPortfolioHoldingReport);
    router.get("/getfamilyserialnumber/:FamilyName", auth, client.GetFamilySerialNumber);
    router.post("/savekycmodificationlog", auth, client.SaveClientKycModificationLog);
    router.get("/getaccountlockedcount/:ClientId", auth, client.GetClientAccountLockedCount);
    router.get("/getkycmodificationlog/:ClientId/:ClientKycProfileId/:ModificationType", auth, client.GetClientKycModificationLog);
    router.get("/getallocationmodificationlog/:ClientId", auth, client.GetClientAssetAllocationModificationLog);
    router.get("/getaccountmodificationlog/:ClientId/:ClientAccountId", auth, client.GetClientAccountModificationLog);
    router.get("/getmandatemodificationlog/:ClientId", auth, client.GetClientAccountMandateModificationLog);
    router.post("/saveaccountrejectionlog", auth, client.SaveClientAccountRejectionLog);
    router.post("/savesupervisorrejectionlog", auth, client.SaveClientSupervisorRejectionLog);

    router.get("/sendbulkcredentials", client.SendBulkClientCredentials);

    app.use("/api/client", router);
};