module.exports = app => {
  const transaction = require("../controllers/transaction.controller");
  const auth = require("../middlewares/auth");
  const authApi = require("../middlewares/authapi");

  var router = require("express").Router();

  router.post("/saveclienttransation", auth, transaction.SaveClientTransation);
  router.post("/saveclienttransationportfolio", auth, transaction.SaveClientTransationPortfolio);
  router.get("/getclienttransactionbyid/:Id", auth, transaction.GetClientTransactionById);
  router.get("/transactionportfoliotypebyclienttransactionid/:Id", auth, transaction.GetClientTransactionPortfolioTypeByClientTransactionId);
  router.get("/getclienttransactionportfolio/:ClientTransactionId/:ClientTransactionPortfolioTypeId", auth, transaction.GetClientTransactionPortfolio);
  router.get("/gettransactiondetails/:Id", auth, transaction.GetClientTransactionDetails);
  router.get("/getbuywealthlumpsumallocation/:ClientTransactionPortfolioId", auth, transaction.GetBuyWealthLumpsumAllocation);
  router.get("/getbuywealthsipallocation/:ClientTransactionPortfolioId", auth, transaction.GetBuyWealthSipAllocation);
  router.get("/getbuytaxlumpsumallocation/:ClientTransactionPortfolioId", auth, transaction.GetBuyTaxLumpsumAllocation);
  router.get("/getbuytaxsipallocation/:ClientTransactionPortfolioId", auth, transaction.GetBuyTaxSipAllocation);
  router.get("/getbuyshorttermlumpsumallocation/:ClientTransactionPortfolioId", auth, transaction.GetBuyShortTermLumpsumAllocation);
  router.get("/getbuyshorttermsipallocation/:ClientTransactionPortfolioId", auth, transaction.GetBuyShortTermSipAllocation);
  router.get("/getbuycommoditieslumpsumallocation/:ClientTransactionPortfolioId", auth, transaction.GetBuyCommoditiesLumpsumAllocation);
  router.get("/getbuycommoditiessipallocation/:ClientTransactionPortfolioId", auth, transaction.GetBuyCommoditiesSipAllocation);
  router.get("/getsellportfolioallocation/:ClientTransactionId", auth, transaction.GetSellPortfolioAllocation);
  router.get("/getsellswpallocation/:ClientTransactionId", auth, transaction.GetSellSWPAllocation);
  router.post("/saveclienttransactionportfolioallocation", auth, transaction.SaveClientTransactionPortfolioAllocation);
  router.post("/saveclienttransactionportfoliosipallocation", auth, transaction.SaveClientTransactionPortfolioSipAllocation);
  router.post("/saveclienttransactionportfolioamount", auth, transaction.SaveClientTransactionPortfolioAmount);
  router.post("/saveclienttransactionportfoliosipamount", auth, transaction.SaveClientTransactionPortfolioSipAmount);
  router.post("/saveclienttransactionportfoliomessage", auth, transaction.SaveClientTransactionPortfolioMessage);
  router.post("/saveclienttransactionallocation", auth, transaction.SaveClientTransactionAllocation);
  router.post("/saveclienttransactionsipcancelallocation", auth, transaction.SaveClientTransactionSIPCancelAllocation);
  router.post("/saveclienttransactionpayment", auth, transaction.SaveClientTransactionPayment);
  router.post("/saveclienttransactionsippayment", auth, transaction.SaveClientTransactionSIPPayment);
  router.post("/deleteclienttransactionportfolio", auth, transaction.DeleteClientTransationPortfolio);
  router.get("/getpaymentdocument/:ClientTransactionId/:ClientTransactionPortfolioId", auth, transaction.GetClientTransactionPaymentDocument);
  router.post("/saveclienttransactionrejection", auth, transaction.SaveClientTransactionRejection);
  router.post("/saveclienttransactionapproval", auth, transaction.SaveClientTransactionApproval);
  router.post("/saveclientsiptransactionapproval", auth, transaction.SaveClientSIPTransactionApproval);
  router.post("/saveclientselltransactionapproval", auth, transaction.SaveClientSellTransactionApproval);
  router.post("/saveclientsellswptransactionapproval", auth, transaction.SaveClientSellSWPTransactionApproval);
  router.post("/saveclientcancelswptransactionapproval", auth, transaction.SaveClientCancelSWPTransactionApproval);
  router.post("/saveadminsellswptransactionapproval", auth, transaction.SaveAdminSellSWPTransactionApproval);
  router.get("/getonlinepaymentdetails/:Id", auth, transaction.GetClientTransactionOnlinePaymentDetail);
  router.post("/saveadmintransaction", auth, transaction.SaveAdminTransaction);
  router.post("/saveadmintransactionapproval", auth, transaction.SaveAdminTransactionApproval);
  router.get("/getnewtrademarketvalue/:Id", auth, transaction.GetNewTransactionPortfolioMarketValue);
  router.get("/getotherportfolioschemes", auth, transaction.GetOtherPortfolioSchemes);
  router.get("/getotherportfoliosipschemes", auth, transaction.GetOtherPortfolioSIPSchemes);
  router.get("/getfoliolist/:ClientAccountId/:BSESchemeId", auth, transaction.GetTransactionUnitLedgerFolioList);
  router.post("/saveclientremark", auth, transaction.SaveTransactionClientRemark);
  router.post("/canceltrade", auth, transaction.CancelTrade);
  router.post("/cancelautotrade", auth, transaction.CancelAutoTrade);
  router.get("/getsipcancelallocation/:ClientAccountId/:ClientTransactionPortfolioId/:TransactionPortfolioTypeId", auth, transaction.GetCancelSipAllocation);
  router.get("/getsipholding/:PortfolioTypeId/:ClientAccountId", auth, transaction.GetActiveSIPPortfolioHolding);
  router.get("/getyearcompletedpurchase/:PortfolioTypeCode/:PortfolioTypeId/:ClientTransactionId", auth, transaction.GetFeedTransactionYearsCompletedPurchaseData);
  router.get("/getclientaccountsholding/:PortfolioTypeCode/:ClientTransactionId", auth, transaction.GetTransactionClientAccountsHolding);
  router.get("/getbuylogic/:ClientTransactionId", auth, transaction.GetBuyLogicData);
  router.get("/getselllogic/:ClientTransactionId", auth, transaction.GetSellLogicData);
  router.get("/downloadbuyallocation/:ClientTransactionId", auth, transaction.DownloadBuyAllocation);
  router.get("/downloadsellallocation/:ClientTransactionId", auth, transaction.DownloadSellAllocation);
  router.post("/getintraswitchschemes", auth, transaction.GetIntraSwitchSchemes);
  router.get("/getintraswitchportfolioallocation/:ClientTransactionId", auth, transaction.GetIntraSwitchPortfolioAllocation);
  router.post("/saveintraswitchportfolioallocation", auth, transaction.SaveIntraSwitchPortfolioAllocation);
  router.get("/getintraswitchallocation/:ClientTransactionId", auth, transaction.GetIntraSwitchAllocation);
  router.post("/saveintraswitchallocation", auth, transaction.SaveIntraSwitchAllocation);
  router.post("/saveclienttransactionrejectionintraswitch", auth, transaction.SaveClientTransactionRejectionIntraSwitch);
  router.post("/saveclientintraswitchtransactionapproval", auth, transaction.SaveClientIntraSwitchTransactionApproval);
  router.post("/getstpswitchschemes", auth, transaction.GetSTPSwitchSchemes);
  router.get("/getstpswitchportfolioallocation/:ClientTransactionId/:AllocationId", auth, transaction.GetSTPSwitchPortfolioAllocation);
  router.get("/getstpfrequency/:ProductCode", auth, transaction.GetSTPFrequency);
  router.get("/getstpschemedetails/:ProductCode/:Frequency", auth, transaction.GetSTPSchemeDetails);
  router.post("/savestpswitchportfolioallocation", auth, transaction.SaveSTPSwitchPortfolioAllocation);
  router.get("/getstpswitchallocation/:ClientTransactionId", auth, transaction.GetSTPSwitchAllocation);
  router.post("/savestpswitchallocation", auth, transaction.SaveSTPSwitchAllocation);
  router.post("/saveadminstpswitchportfolioallocation", auth, transaction.SaveAdminStpSwitchPortfolioAllocation);
  router.post("/saveclientstpswitchtransactionapproval", auth, transaction.SaveClientSTPSwitchTransactionApproval);
  router.post("/saveadminstpswitchtransactionapproval", auth, transaction.SaveAdminSTPSwitchTransactionApproval);
  router.get("/getclienttransactionallocationsell/:ClientTransactionId", auth, transaction.GetClientTransactionAllocationSell);
  router.get("/getportfoliomarketvalue/:PortfolioTypeCode/:ClientTransactionId", auth, transaction.GetSellTransactionPortfolioMarketValue);
  router.get("/getexistingswp/:ClientTransactionId", auth, transaction.GetClientTransactionPortfolioExistingSWP);
  router.get("/getexistingstp/:ClientTransactionId", auth, transaction.GetClientTransactionExistingSTP);
  router.post("/savestpcancelallocation", auth, transaction.SaveSTPCancelAllocation);
  router.post("/saveadminstpcancelallocation", auth, transaction.SaveAdminSTPCancelAllocation);
  router.post("/saveclientstpcanceltransactionapproval", auth, transaction.SaveClientSTPCancelTransactionApproval);
  router.post("/saveadminstpcanceltransactionapproval", auth, transaction.SaveAdminSTPCancelTransactionApproval);
  router.get("/gettransactionhistory/:PANCardNumber", auth, transaction.GetFeedTransactionBSEOrderStatus);
  router.post("/savetransactiontagging", auth, transaction.SaveTransactionTagging);
  router.post("/resendtransactionlink", auth, transaction.ResendClientTransactionLink);
  router.post("/resendtransactionpaymentlink", auth, transaction.ResendClientTransactionPaymentLink);
  router.post("/addbuyschedule", authApi, transaction.AddBondBuyMFSchedule);
  router.post("/revisebuyschedule", authApi, transaction.ReviseBondBuyMFSchedule);
  router.post("/cancelbuyschedule", authApi, transaction.CancelBondBuyMFSchedule);
  router.post("/saveadminselltransactionapproval", auth, transaction.SaveAdminSellTransactionApproval);
  router.get("/getrecenttransactions/:AssociateId/:FromDate/:ToDate", auth, transaction.GetRecentTransactionList);
  router.get("/getpendingtransactions/:AssociateId/:FromDate/:ToDate", auth, transaction.GetPendingTransactionList);
  router.get("/getrecommendedtransactions/:AssociateId", auth, transaction.GetRecommendedTransactionList);
  router.get("/getremindertransactions/:AssociateId/:FromDate/:ToDate", auth, transaction.GetReminderTransactionList);
  router.post("/saveclientrecommendedsellrecord", auth, transaction.SaveClientRecommendedSellRecord);

  router.get("/checkbsepayment", transaction.CheckBSEPayment);

  app.use("/api/transaction", router);
};