[program:kinntegra-api]
command=node index.js
directory=/app/kinntegra-api
autostart=true
autorestart=true
startsecs=5
startretries=5
stopsignal=TERM
stopwaitsecs=15
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/supervisor/kinntegra-api.err.log
stdout_logfile=/var/log/supervisor/kinntegra-api.out.log
